project:
  type: website
  output-dir: docs

website:
  title: "Term Project Proposal"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Digital Marketing"
        href: digital-marketing.qmd
      - text: "Marketing Analytics"
        href: marketing-analytics.qmd
      - text: "Presentation"
        href: presentation.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

